Hexandria game REST API beta
java-park-mail-ru/civilization-02-2017 pull request #1
Opened 2017-02-26 10:47 UTC by Intaco

2017-02-26 23:10 UTC, Intaco commented
Дока по API:
https://app.swaggerhub.com/api/aorel/HexandriaAPI/0.1.0

2017-02-27 15:26 UTC, KSolovyev commented
Давайте сократим количество ручек. Вместо user-get и signup сделаем GET /user/ и POST /user/. В принципе, можно смену пароля сделать через  PUT, но это по желанию.

2017-02-28 08:49 UTC, KSolovyev requested changes

2017-02-28 08:49 UTC, KSolovyev commented on src/test/java/AuthorizationTest.java
> +public class AuthorizationTest extends AbstractTestCase{
Пустой класс, надо убрать

2017-02-28 08:49 UTC, KSolovyev commented on src/test/java/AbstractTestCase.java
> +public abstract class AbstractTestCase {
Это тоже какой-то черновой класс, надо убрать

2017-02-28 08:49 UTC, KSolovyev commented on src/main/java/sample/auth/ERRORSTATE.java
> +    FORBIDDEN(403), NOT_FOUND(404), BAD_REQUEST(400), CONFLICT(409);
Conflict в http означает, что запрос не был обработан из-за гонок за какой-то ресурс внутри сервера. Это очень редкая ошибка. В случае совпадения логинов нужно говорить 403 Forbidden. Осталось придумать как отличать ошибку с неправильным паролем от ошибки с совпадающим логином.

2017-02-28 08:49 UTC, KSolovyev commented on src/main/java/sample/AccountService.java
> +    public Optional<ErrorResponse> register(AuthorizationCredentials credentials) {
Есть два предложения: 
1) переписать на List<>
2) уйти от семантики контроллера, т.е. не использовать в сервисе всякие Response и коды ответа. Это зона ответственности контроллера.
Это замечание Optional<>
И надеюсь все члены вашей команды понимают, что здесь написано)

2017-02-28 08:49 UTC, KSolovyev commented on src/main/java/sample/AccountService.java
> +    public Optional<User> loadUser(AuthorizationCredentials credentials) {
не используется

2017-02-28 08:49 UTC, KSolovyev commented on src/main/java/sample/UserController.java
> +     * Данный метод вызывается с помощью reflection'a, поэтому Spring позволяет инжектить в него аргументы.
комментарий надо убрать

2017-02-28 08:49 UTC, KSolovyev commented on src/main/java/sample/UserController.java
> +        httpSession.setAttribute(httpSession.getId(), user.getlogin());
Вот в этом месте, мне кажется, вы все усложняете. Зачем сохранять логин по генеренному ключу?Гораздо проще константу завести

2017-02-28 08:49 UTC, KSolovyev commented on src/main/java/sample/auth/utils/AuthorizationUtils.java
> +    public static String generateSHA512(String passwordToHash) {
не используется и не надо. Писать любое шифрование руками - это плохая идея. Надо использовать готовые, проверенные инструменты. В spring.security они есть

2017-02-28 08:49 UTC, KSolovyev commented on src/main/java/sample/UserController.java
> +     * Данный метод вызывается с помощью reflection'a, поэтому Spring позволяет инжектить в него аргументы.
комментарий надо убрать

2017-02-28 08:49 UTC, KSolovyev commented on src/main/java/sample/auth/utils/RequestValidator.java
> +        final String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
а как же поддержка национальных доменов?)
А еще длина поддомена не может быть больше 63 символов, а общая длина хоста не более  255.
В общем давайте для этого заиспользуем apache-validator
```
        <dependency>
            <groupId>commons-validator</groupId>
            <artifactId>commons-validator</artifactId>
            <version>1.6</version>
        </dependency>
```

2017-02-28 08:49 UTC, KSolovyev commented on src/main/java/sample/auth/ERRORSTATE.java
> +public enum ERRORSTATE {
СamelCase, пожалуйста

2017-02-28 08:49 UTC, KSolovyev commented on src/main/java/sample/auth/dao/UserDAO.java
> +public class UserDAO {
Сделайте это сервисом, пожалуйста. Давайте избавимся от статических полей и методов. Или же вынесите все в AccountService. Сейчас можно совсем без DAO

2017-02-28 08:49 UTC, KSolovyev commented on src/main/java/sample/auth/utils/AuthorizationUtils.java
> +    //Временное решение, в дальнейшем будем генерить ID в БД
сделайте из комента TODO

2017-03-01 18:29 UTC, KSolovyev commented
отпишитесь, пожалуйста, как можно будет еще раз посмотреть

2017-03-12 19:09 UTC, KSolovyev commented
еще не все?

2017-03-13 10:57 UTC, Intaco commented
Готово.

2017-03-13 20:57 UTC, KSolovyev requested changes

2017-03-13 20:57 UTC, KSolovyev commented on src/tests/ApplicationTest.java
> +//        response = restTemplate.getForObject(USER_URI, );
убрать

2017-03-13 20:57 UTC, KSolovyev commented on src/main/java/sample/UserController.java
> +            errorString.append(e.getErrorText());
зачем так-то? Можно сделать модельку, в которой одно из полей будет List<ErrorResponse> errors. Оно будет автоматически сериализовано в json-массив

2017-03-15 09:53 UTC, Metalluga commented on src/tests/ApplicationTest.java
> +//        response = restTemplate.getForObject(USER_URI, );
Не подскажете, как по-другому делать запрос от авторизованного пользователя? Просто без этого запрос всегда будет возвращать, что пользователь не авторизован

2017-03-16 15:48 UTC, KSolovyev commented on src/tests/ApplicationTest.java
> +//        response = restTemplate.getForObject(USER_URI, );
убрать закоментированный код надо, а не функционал)

2017-03-16 16:25 UTC, Metalluga commented on src/tests/ApplicationTest.java
> +//        response = restTemplate.getForObject(USER_URI, );
Оу. Туплю чего-то)

2017-03-28 00:28 UTC, Metalluga commented
Дико извиняюсь, что так долго исправлял. _Здесь картинка слоупока_

2017-03-28 09:26 UTC, merged