К 2 РК
java-park-mail-ru/civilization-02-2017 pull request #2
Opened 2017-03-30 11:10 UTC by Intaco

Работа с БД Postgres + тесты на H2

2017-04-02 21:59 UTC, d-frolov requested changes
Общая просьба по коду.

Делайте на каждом файле Code->Reformat Code для более аккуратного форматирования

2017-04-02 21:59 UTC, d-frolov commented on src/main/java/com/hexandria/auth/common/user/UserManager.java
> +import org.omg.CORBA.Environment;
Проверьте и удалите неактуальные зависимости, например вот эту

2017-04-02 21:59 UTC, d-frolov commented on src/main/java/com/hexandria/auth/common/AuthData.java
> +public class AuthData {
Этот класс, у вас по сути является абстрактным? Укажите это явно. Хорошая практика, когда у вас класс является либо final либо абстрактным. Позволяет избежать неприятностей

2017-04-02 21:59 UTC, d-frolov commented on src/main/java/com/hexandria/auth/common/user/IUserManager.java
> +public interface IUserManager {
Замечание не обязательное для исправления: IUserManager - это C++ стиль наименований интерфейсов.

2017-04-02 21:59 UTC, d-frolov commented on src/main/java/com/hexandria/auth/common/user/IUserManager.java
> +    UserEntity createUser(UserEntity userEntity);
Я заметил, что в реализации этого интерфейса вы начали использовать аннотации Nullable, NotNull.  Хорошая практика начинать разметку этими аннотациями интерфейсы. Как параметры функций, так и возвращаемые значения. Тогда Idea заставит вас разметить и класс реализации и будет проверять использование интерфейсов в других участках кода.

2017-04-02 21:59 UTC, d-frolov commented on src/main/java/com/hexandria/auth/common/user/UserManager.java
> +    protected EntityManager entityManager;
зачем protected? вы хотите наследоваться от этого класса? Это плохая идея

2017-04-02 21:59 UTC, d-frolov commented on src/main/java/com/hexandria/auth/common/user/UserManager.java
> +    public void updateUser(UserEntity userEntity) {
Я посмотрел, этот метод вызывается у вас только внутри changeUserPassword. Тогда почему он не private? да еще вынесен в интерфейс. Интерфейс - это API, а оно должно быть лаконичным

2017-04-02 21:59 UTC, d-frolov commented on src/main/java/com/hexandria/UserController.java
> +    private final UserManager userManager;
А зачем вы вообще делали интерфейс, если у вас в контроллере ссылка не на него, а на имплементацию?

2017-04-02 21:59 UTC, d-frolov commented on src/main/java/com/hexandria/UserController.java
>          final ErrorResponse sessionError = RequestValidator.validateNotAuthorizedSession(httpSession);
У вас во всех методах одни и те-же 4 строчки кода. Может как-то покомпактнее?

2017-04-02 21:59 UTC, d-frolov commented on src/main/java/com/hexandria/auth/common/user/UserManager.java
> +    public UserEntity getUserById(String id) {
Давайте немного порядка наведем. Ваш сервис UserManager с одной стороны скрывает всю работу с БД от вышестоящих сервисов, но с другой стороны его не должно волновать откуда и в каком виде вышестоящие сервисы берут входные данные. Именно вышестоящие сервисы должные сделать проверку типа содержимого и преобразовать из String в int id пользователя

2017-04-02 21:59 UTC, d-frolov commented on src/main/java/com/hexandria/auth/common/user/UserManager.java
> +    public Either<UserEntity, List<ErrorResponse>> login(AuthData credentials) {
А зачем вы передаете ошибки через  возвращаемые значения? Почему бы не сделать собственный класс исключений UserManagerException, куда можно добавить как параметр - ErrorState.

Да, кстати, как у вас обрабатываются исключения работы с БД? вроде неправильного запроса, разрыва соединения и тп? логичнее и этот тип исключений обернуть в ваше собственное исключение со статусом 500

2017-04-03 21:02 UTC, Intaco commented on src/main/java/com/hexandria/auth/common/user/UserManager.java
> +    public void updateUser(UserEntity userEntity) {
Планировал в дальнейшем использование данного метода помимо changeUserPassword, поэтому и вынес отдельно. Может, лучше все же оставить?

2017-04-03 21:03 UTC, Intaco commented on src/main/java/com/hexandria/auth/common/user/UserManager.java
> +    public Either<UserEntity, List<ErrorResponse>> login(AuthData credentials) {
Ошибки возвращаю списком ErrorState'ов, чтобы можно было удобно их в дальнейшем использовать и выводить в UserController'е. Вся суть вывода именно листа данного типа в текущей реализации в том, чтобы весь перехват и обработка ошибок производились на уровень ниже UserController'а, а в нем производился только вывод результатов. (Чтобы код был ненагроможден и удобочитаем).
По поводу БД:
Сейчас есть методы 
getUserByLogin
createUser
getUserById
updateUser
Сейчас бросают эксепшн вверх, за исключением NoResultException в getUserByLogin - там просто возвращается null в случае если ничего не найдено. 
Хотелось бы обрабатывать их на уровне manager'а, чтобы опять же до контроллера ничего не долетало. Честно говоря, пока не заморачивались, потому что ошибки вроде разрыва соединения редки, а при текущей 'сложности' некорректных запросов быть не должно, но безусловно подобный механизм надо обдумать и сделать. Единственное, пока не до конца ясно, в каком месте что и как перехватывать и где обрабатывать. Можете дать совет, пожалуйста?

2017-04-03 21:19 UTC, Intaco commented on src/main/java/com/hexandria/UserController.java
>          final ErrorResponse sessionError = RequestValidator.validateNotAuthorizedSession(httpSession);
Они часто похожие, но почти всегда чем-нибудь отличаются: логгируются разные параметры запроса, где-то есть сессия, где-то ее нет; где-то проверяется, залогинен ли юзер, для других методов это не нужно. POST/GET и т.п., поэтому не знаю, как тут можно сократить количество кода.

2017-04-03 21:26 UTC, Intaco commented on src/main/java/com/hexandria/auth/common/AuthData.java
> +public class AuthData {
Не совсем, класс используется в ряде запросов как параметры. В принципе, можно было бы сделать его абстрактным, а во всех запросах использовать ChangePasswordData, но как-то оно не совсем логично будет смотреться, а использование абстрактного класса в качестве RequestBody вроде как не работает.

2017-04-09 21:23 UTC, KSolovyev commented
отпишитесь, пожалуйста, как закончите

2017-04-10 13:17 UTC, KSolovyev commented
@d-frolov Посмотри, ребята говорят, что закончили

2017-04-11 23:45 UTC, d-frolov requested changes
так, кажется часть моих замечаний прошлый раз не ушла к вам как реквест. Сорри

2017-04-11 23:45 UTC, d-frolov commented on src/main/java/com/hexandria/auth/common/user/UserManager.java
> +    UserEntity getUserById(Integer id);
Ну доведите тогда уж дело до конца и проаннотируйте и параметры методов

2017-04-11 23:45 UTC, d-frolov commented on src/main/java/com/hexandria/auth/common/user/UserManager.java
> +    Either<UserEntity, List<ErrorResponse>> login(AuthData credentials);
А чего с ошибками в итоге? Мне, честно говоря, очень не нравится такой подход
Either<UserEntity, List<ErrorResponse>>

Все-таки как правило в Java приятно, что методы возвращают результат выполнения, а ошибки прокидываются через  исключения

2017-04-11 23:45 UTC, d-frolov commented on src/main/java/com/hexandria/auth/common/user/IUserManager.java
> +    UserEntity getUserById(Integer id);
Пожалуйста доаннотируйте все возвращаемые значения и параметры методов интерфейса
NotNull Nullable

2017-04-16 18:55 UTC, Metalluga commented on src/main/java/com/hexandria/auth/common/user/UserManager.java
> +    Either<UserEntity, List<ErrorResponse>> login(AuthData credentials);
У нас этот вопрос возник ещё на первом РК, Константина такое решение устроило

2017-04-20 13:26 UTC, d-frolov commented
ок, принято

2017-04-20 13:26 UTC, merged